import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import CatagoryDataLoad from "@/components/CatagoryDataLoad";
import { Suspense } from "react";
import MarqueeComp from "@/components/MarqueeComp";

const notoserifbenfali = Noto_Serif_Bengali({
  // variable: "--font-geist-sans",
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoserifbenfali.className}  h-full antialiased `}

    >
      <body className="min-h-full flex flex-col">
        <NavBar></NavBar>
        <Suspense fallback={"Loading........"}>
          <CatagoryDataLoad></CatagoryDataLoad>
          <MarqueeComp></MarqueeComp>
        </Suspense>
        
        <main className=" mt-5">

          {children}
        </main>
      </body>
    </html>
  );
}

